openaerostruct/examples/run_CRM.py
openaerostruct/structures/spatial_beam_states.py
openaerostruct/structures/struct_groups.py
openaerostruct/structures/total_loads.py
openaerostruct/tests/test_wingbox_analysis.py

Running wingbox analysis with `SpatialBeamAlone` now checks for `distributed_fuel_weight` and `struct_weight_relief`. However currently we still automatically add fuel vol comp for all wingbox cases.

added logic for wingbox analysis, added test

---

openaerostruct/geometry/radius_comp.py
openaerostruct/structures/utils.py

closes #221
On a large mesh (177x51) for model with just this component:
- Execution time for 10 calls to linearize:  1.0 seconds -> .001 seconds
- Memory footprint during check partials: 240 MB -> 180 MB.

Sparsified derivative on geo radius comp.

---

openaerostruct/utils/plot_wingbox.py

Issue #300 showed a bug with the newest version of matplotlib. This PR resolves that by removing the equal axis call to the 3D plot of `plot_wingbox`. The plotting code still works as intended and appears to have the correct view.
See https://github.com/matplotlib/matplotlib/issues/1077/ for details on why 3D plots can't have equal axes.
_Select the appropriate type(s) that describe this PR_
GUI testing only; no CI. Ran locally on newest matplotlib.
_Put an `x` in the boxes that apply._

Bugfix for most recent matplotlib version

---

openaerostruct/geometry/utils.py

Use integer division when appropriate. This solves the following error
that appeared during tests:
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer
My system details are
>>> import platform, sys
>>> info = platform.uname()
>>> (info.system, info.version), (info.machine, info.processor), sys.version
(('Linux', '#40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019'), ('x86_64', 'x86_64'), '3.6.9     (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]')
This was causing 14 tests to fail when running on python 3.6, namely
test_aero_analysis_no_symmetry.py:Test.test
test_aero_analysis_no_symmetry_wavedrag.py:Test.test
test_aero_opt_no_symmetry.py:Test.test
test_aero_opt_wavedrag.py:Test.test
test_geometry_mesh_transformations.py:Test.test_dihedral …

Bug fix: float division was used instead of integer division

---

.travis.yml
README.md
openaerostruct/docs/installation.rst

Follow-up to our discussion about matching up OpenMDAO version and OAS version well.
This OAS version is tied to OM 3.1.0 which released today.
All tests pass locally with OM 3.1.0.

Updated readme and installation guide

---

openaerostruct/docs/aerostructural_wingbox_walkthrough.rst
openaerostruct/docs/wingbox_mpt_opt_example.py

Reducing confusion in the wingbox walkthrough example. The engine masses were being subtracted from W0 and added back in a way that caused confusion. The optimization problem remains unchanged, just some changes to the setup.
Ran the example locally and confirmed results do not change.

Reducing confusion in the wingbox walkthrough example

---

openaerostruct/tests/test_multi_aero_ffd.py
openaerostruct/tests/test_multipoint_aero.py
openaerostruct/tests/test_multipoint_aero_ffd.py

Some multipoint tests (which also appear in the docs) were not actually multipoint, but they were multi-aircraft/ morphing. This is because the geometry groups were added under each aero points repeatedly and individually, although the geometry should be consistent between all aero points.
This PR fixes #284, by removing the geometry groups from each aero point, adding them outside the aero point groups, and connecting the single geometry to each aero point.  
I also needed to update the reference values in `test_multipoint_aero.py`, because the optimization problem it solves is changed.
- Code style update (formatting, renaming)
- [ x ] I have run unit and regression tests which pass locally with my changes

Fixed multipoint tests

---

openaerostruct/integration/aerostruct_groups.py
openaerostruct/tests/test_aerostruct.py
openaerostruct/tests/test_aerostruct_analysis_compressible.py

I was running a case where I needed to compute the derivative of an OpenAerostruct model with respect to beta, and found that it wasn't promoted. It was actually partially promoted in a couple of spots, but some important ones were missing.
closes #342
- Breaking change (non-backwards-compatible fix or feature)
Not a major "breaking" change, but since version 3.2 of OpenMDAO, auto-indepvarcomps are automatically created for unconnected inputs. To prevent ambiguity, if inputs with different units are promoted together, OpenMDAO raises an error. You can work around this by adding that input to your top level indepvarcomp, but a more correct way is to use `group.set_input_defaults` to define the source units (but …

Promote beta (sideslip angle) to the top of AerostructGroup

---

setup.py

Update setup.py to restrict OpenMDAO range.

Update setup.py for OM reqs

---

README.md

To avoid having to update OAS every time OM changes, this makes the readme and docs more restrictive about the required versions.

Readme update for OM versions

---

.gitignore
openaerostruct/examples/run_scaneagle.py
openaerostruct/integration/aerostruct_groups.py
openaerostruct/tests/test_scaneagle.py

Addresses a problem where sweep and taper were promoted as outputs instead of inputs in the aerostructural geometry. Also fixes the ScanEagle example, which was broken since wing twist was both a design variable and constraint. Added a test for the ScanEagle.
This PR resolves #367.

Fixes aerostruct geometry promotion and ScanEagle example

---

.github/workflows/oas.yml
README.md
openaerostruct/docs/installation.rst

This will enable people to install OpenAeroStruct with `pip install openaerostruct`
1 day

Add push to the Python Package Index

---

README.md
setup.py

This PR adds a description and URL to the setup.py file so it shows up on PyPI's website.

Added info to setup.py for PyPI

---

.github/workflows/oas.yml
.readthedocs.yaml

NOTE: RTD build is currently failing, and I believe [this](https://github.com/readthedocs/readthedocs.org/pull/10287) will fix the issue. This fix is not released yet so we'll wait for a while.
Fixed the build issue of the oldest OpenMDAO.
In the oldest build, we've been failing to build wheel for OpenMDAO (I don't know exactly why, but we don't need to care about it because the latest build doesn't have this error). Then, the previous versions of pip switch to `setup.py install` which works, but the latest pip deprecated it, hence we're seeing the error.
In this PR, I pinned the pip version for the oldest build so that it switches to the `setup.py install` method to build OM. This workaround does not affect the latest build. 
Copied from an old build log:
```
DEPRECATION: openmdao was …
```

Fixing old OpenMDAO build

---

.github/workflows/oas.yml

This PR fixed the build with the oldest dependencies (specifically, the installation of OpenMDAO 3.15.0)
Soon

Fixing oldest OpenMDAO install

---

.github/workflows/oas.yml
openaerostruct/mphys/aero_builder.py
openaerostruct/mphys/tests/test_aero_builder.py
openaerostruct/mphys/utils.py

This is related to https://github.com/OpenMDAO/mphys/pull/158 and https://github.com/smdogroup/funtofem/pull/192 and allows for aerostructural analysis with multiple bodies
a week

Adding `get_tagged_indices` to mphys wrapper

---

.readthedocs.yaml
openaerostruct/docs/user_reference/mesh_surface_dict.rst
openaerostruct/examples/drag_polar_ground_effect.py
openaerostruct/examples/rectangular_wing/drag_polar.py
openaerostruct/examples/rectangular_wing/mphys_example.py
openaerostruct/examples/rectangular_wing/opt_chord.py
openaerostruct/examples/rectangular_wing/opt_twist.py
openaerostruct/examples/rectangular_wing/run_rect_wing.py
openaerostruct/examples/rectangular_wing/run_roll.py
openaerostruct/geometry/geometry_group.py
openaerostruct/geometry/geometry_mesh.py
openaerostruct/geometry/geometry_mesh_transformations.py
openaerostruct/geometry/tests/test_geometry_mesh_transformations.py
openaerostruct/geometry/tests/test_vsp_mesh.py
openaerostruct/geometry/utils.py
openaerostruct/integration/aerostruct_groups.py
openaerostruct/tests/test_aero_atmos.py
openaerostruct/tests/test_simple_rect_aero.py
openaerostruct/tests/test_simple_rect_aero_roll.py
openaerostruct/tests/test_simple_rect_aero_sideslip.py
openaerostruct/tests/test_simple_rect_aero_wo_symmetry.py
openaerostruct/tests/test_simple_rect_right_aero.py
openaerostruct/utils/check_surface_dict.py

With this PR, OAS will check a user-defined dicts (mesh dict or surface dict) and warn if the user provides a key that is not implemented or used in OAS.
For example, some examples and tests provide the `chord` key when creating a mesh, but the key `chord` does not exist and therefore never used. I fixed them to `root_chord`, the one actually used.
I also removed unused keys from other tests.
The current documentation and docstrings say the `chord_cp` variable is the actual chord value in meters, but what the code (ScaleX component) actually does is that it applies the chord scaler to the initial mesh. Therefore `chord_cp` is actually a dimensionless chord scaler.  
This PR fixes the documentation and docstrings.
Also, I updated the surface dict documentation.
(It's a little too late but …

Added dict key validation & updated documentation

---

openaerostruct/geometry/utils.py

Adding argument to scale incoming vsp models. Useful for when geometry model has differing units from analysis model
A week

Adding scale factor to generate_vsp_surfaces

---

openaerostruct/utils/plot_wing.py
openaerostruct/utils/plot_wingbox.py

Fix plot_wing.py to work for matplotlib v3.8+.
The `dist` attribute for 3-D plots has been deprecated in recent matplotlib versions.
See related Issue #423
Also made the 3-D view behavior consistent in plot_wingbox.py (the 3-D view should not reset if the iteration is changed).
1 day
Code review should only take a few minutes.
Bugfix (non-breaking change which fixes an issue)
Ran the run_CRM.py and run_aerostruct_uCRM_multipoint.py examples, and also confirmed that the views don't reset it the iteration is changed.
Tested with matplotlib versions:
* 3.6.0
* 3.7.0
* 3.8.0
* 3.8.3

Fix plot_wing.py to work for matplotlib v3.8+

---

openaerostruct/geometry/geometry_group.py
openaerostruct/structures/tube_group.py
openaerostruct/structures/wingbox_group.py
openaerostruct/tests/test_aero_analysis_no_symmetry_wavedrag.py
openaerostruct/tests/test_aero_opt_wavedrag.py
openaerostruct/tests/test_aerostruct.py
openaerostruct/tests/test_aerostruct_analysis.py
openaerostruct/tests/test_aerostruct_analysis_Sref.py
openaerostruct/tests/test_aerostruct_analysis_compressible.py
openaerostruct/tests/test_aerostruct_engine_thrusts.py
openaerostruct/tests/test_aerostruct_ffd.py
openaerostruct/tests/test_aerostruct_groundeffect.py
openaerostruct/tests/test_aerostruct_point_loads.py
openaerostruct/tests/test_aerostruct_wingbox_+weight_analysis.py
openaerostruct/tests/test_aerostruct_wingbox_analysis.py
openaerostruct/tests/test_aerostruct_wingbox_fuel_vol_constraint_opt.py
openaerostruct/tests/test_aerostruct_wingbox_wave_fuel_vol_constraint_opt.py
openaerostruct/tests/test_multipoint_parallel.py
openaerostruct/tests/test_multipoint_wingbox_aerostruct.py
openaerostruct/tests/test_scaneagle.py
openaerostruct/tests/test_simple_rect_AS.py
openaerostruct/tests/test_v1_aero_opt.py
openaerostruct/tests/test_v1_aerostruct_analysis.py
openaerostruct/tests/test_wingbox_analysis.py
openaerostruct/utils/interpolation.py
openaerostruct/utils/testing.py

OpenAeroStruct uses b-splines to interpolate geometric design variable values onto the mesh (either at mesh nodes or panel mid-points), these b-splines are defined over a coordinate range of 0 to 1, so it is necessary to map the spanwise coordinates of the mesh to the same range. In other words, we need to define where on the spline each mesh point interpolates it's design variable value from.
Currently, for all DVs that use this interpolation, we simply linearly space these interpolation points from 0 to 1. This works fine if your mesh has constant spanwise spacing but otherwise produces unintuitive results, it also means that for the same design variable values, changing the spanwise mesh distribution significantly changes the wing geometry.
Additionally, this approach means that for …

Make geometry spline interpolation mesh independent

---

openaerostruct/docs/advanced_features/aerostruct_ffd.rst
openaerostruct/docs/advanced_features/ground_effect.rst
openaerostruct/docs/advanced_features/multiple_surfaces.rst
openaerostruct/docs/advanced_features/multipoint.rst
openaerostruct/docs/advanced_features/multipoint_parallel.rst
openaerostruct/docs/aerostructural_tube_walkthrough.rst
openaerostruct/docs/quick_example.rst
openaerostruct/docs/struct_example.rst
openaerostruct/docs/user_reference/v1_v2_conversion.rst
tests/integration_tests/test_aero_ground_effect.py
tests/integration_tests/test_aerostruct.py
tests/integration_tests/test_aerostruct_ffd.py
tests/integration_tests/test_multiple_aero_analysis.py
tests/integration_tests/test_multipoint_aero.py
tests/integration_tests/test_multipoint_parallel.py
tests/integration_tests/test_struct.py

The test file locations were moved in a previous PR, which broke code blocks in the docs. This PR fixes the paths so they appear again.

Fixed paths to code in docs
