gs_newton.py, prob3c_solution.py
1. Make sure the sub solvers in gs_newton get setup
2. Make sure gs_newton.newton's linear solver is also in gs_newton so that some error checks recgonize it as a solver that needs derivatives.
3. The rest is trailing spaces that my editor stripped.
=> Just a little change to the gs_newton solver so that we get the right warning message

openaerostruct/geometry/geometry_mesh.py, openaerostruct/utils/plot_wing.py
- better logic for checking twist_included
- consistent dimensions for twist
- (hopefully) more consistent numbering of num_iters. @johnjasa  can you double check this
Fixes #97
=> updated a few things in plot_wing

openaerostruct/aerodynamics/aero_groups.py, openaerostruct/functionals/moment_coefficient.py, openaerostruct/utils/plot_wing.py
=> Updated moment coefficient; merging

openaerostruct/aerodynamics/lift_coeff_2D.py
Vectorization and sparsity done for lift_coeff_2D
=> Vectorization and sparsity done

example_deriv_check.py, openaerostruct/aerodynamics/forces.py, openaerostruct/aerodynamics/vortex_mesh.py, openaerostruct/geometry/radius_comp.py, openaerostruct/geometry/utils.py, openaerostruct/structures/create_rhs.py, openaerostruct/utils/testing.py
=> updated viewmat to show three subplots side by side

openaerostruct/aerodynamics/tests/test_assemble_aic.py, openaerostruct/aerodynamics/tests/test_circulations.py, openaerostruct/aerodynamics/tests/test_forces.py, openaerostruct/fortran/config/config.mk, openaerostruct/functionals/moment_coefficient.py, openaerostruct/functionals/tests/test_breguet_range.py, openaerostruct/functionals/tests/test_total_lift_drag.py, openaerostruct/structures/assemble_k.py, openaerostruct/structures/tests/test_assemble_k.py, openaerostruct/transfer/load_transfer.py, openaerostruct/utils/testing.py
=> fixed erroneous NANing tests

openaerostruct/geometry/monotonic_constraint.py, openaerostruct/geometry/tests/test_monotonic_constraint.py
=> updated monotonic constraint to use const sparse jac, added tests

openaerostruct/aerodynamics/aero_groups.py, openaerostruct/aerodynamics/tests/test_wave_drag.py, openaerostruct/docs/more_examples.rst, openaerostruct/docs/more_examples/user_specified_sref.rst, openaerostruct/functionals/total_aero_performance.py, openaerostruct/functionals/total_performance.py, openaerostruct/integration/aerostruct_groups.py, openaerostruct/structures/create_rhs.py, openaerostruct/structures/section_properties_wingbox.py, openaerostruct/structures/spatial_beam_states.py, openaerostruct/structures/tests/test_total_load_derivs.py, openaerostruct/structures/vonmises_wingbox.py, openaerostruct/structures/wing_weight_loads.py, openaerostruct/structures/wingbox_geometry.py, openaerostruct/tests/test_aero_analysis_Sref.py, openaerostruct/tests/test_aerostruct_analysis_Sref.py
=> Added option to specify Sref, fixed units and minor edits

openaerostruct/structures/structural_cg.py
awesome sparcified structural calcs
=> parcified structural cg calcls

openaerostruct/aerodynamics/geometry.py, openaerostruct/functionals/moment_coefficient.py
=> Derivatives for moment component.

openaerostruct/examples/run_aerostruct_uCRM_multipoint.py, openaerostruct/integration/aerostruct_groups.py, openaerostruct/tests/test_aerostruct.py, openaerostruct/tests/test_aerostruct_analysis.py, openaerostruct/tests/test_aerostruct_analysis_Sref.py, openaerostruct/tests/test_aerostruct_ffd.py, openaerostruct/tests/test_aerostruct_wingbox_+weight_analysis.py, openaerostruct/tests/test_aerostruct_wingbox_analysis.py, openaerostruct/tests/test_aerostruct_wingbox_fuel_vol_constraint_opt.py, openaerostruct/tests/test_aerostruct_wingbox_opt.py, openaerostruct/tests/test_aerostruct_wingbox_wave_fuel_vol_constraint_opt.py, openaerostruct/tests/test_multipoint_wingbox_aerostruct.py, openaerostruct/tests/test_multipoint_wingbox_derivs.py, openaerostruct/tests/test_simple_rect_AS.py, openaerostruct/tests/test_v1_aerostruct_analysis.py, openaerostruct/tests/test_v1_aerostruct_opt.py, openaerostruct/tests/test_wingbox_derivs.py, openaerostruct/tests/test_wingbox_distributed_fuel.py
Renaming the Group class to make its function more clear. 
There were unused Geometry imports everywhere that also made things a little confusing
=> Cleanup unused import and rename the AeroStruct -> AeroStructGeometry

openaerostruct/structures/utils.py, openaerostruct/structures/vonmises_tube.py
closes #222 
Didn't see a whole lot of improvement from this change.
=> Vectorize vonmises tube derivatives

openaerostruct/tests/test_v1_aerostruct_opt.py, openaerostruct/transfer/load_transfer.py, openaerostruct/transfer/tests/test_load_transfer.py
Fixes #231
This new version is about 200 times faster for linearize.
=> Rework the load_transfer derivatives to fix a bug and improve performance.

openaerostruct/docs/aero_walkthrough/part_7.py, openaerostruct/utils/plot_wing.py, openaerostruct/utils/plot_wingbox.py
Updated plot_wing to work with OpenMDAO v2.5 and verified it's functional for aero, struct alone, and aerostructural cases.
Addresses #255, #253, and #252
=> Updated plot_wing

openaerostruct/docs/aerostructural_wingbox_walkthrough.rst, openaerostruct/docs/wingbox_mpt_opt_example.py, openaerostruct/integration/aerostruct_groups.py
=> Slightly loosening atol on aerostruct system so it converges well in examples

openaerostruct/docs/requirements.txt, openaerostruct/utils/plot_wing.py, openaerostruct/utils/plot_wingbox.py, openaerostruct/utils/testing.py
There was an old import of sqlitedict that is no longer needed to run plot_wing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.
_Put an `x` in the boxes that apply._
=> Removed sqlitedict as it's no longer needed

README.md
Clarifying that OAS is provided "as is" and that support is not guaranteed.
Readme looks OK on GitHub's rendering.
=> Clarifying support

.travis.yml
Attempting to fix travis-sphinx deploy, which broke on recent changes
_Select the appropriate type(s) that describe this PR_
=> Fixing travis-sphinx deploy

.travis.yml
The documentation is finally working! Need to go back to the root directory before `coveralls`. 
=> Fixed travis.yml

openaerostruct/utils/plot_wing.py, openaerostruct/utils/plot_wingbox.py
A few bugs in the plot functions `plot_wing` and `plot_wingbox` have been fixed.
- Fixed `save_video` method which was broken for the latest version of matplotlib.
- Fixed a bug that the last iteration of the optimization was not displayed in the interactive plot.
- Updated a deprecated attribute. 
No formal testing since it is a post-processing code. I ran them by myself and made sure it works.
=> Fixed plot functions

.github/workflows/oas_push.yml
Explain the goal of this PR, if it addresses an existing issue be sure to link to it. Describe the big picture of your changes here, perhaps using a bullet list if multiple changes are done to accomplish a single goal.  If it accomplishes multiple goals, it would be best to create separate PR's for each. 
_Select the appropriate type(s) that describe this PR_
- New feature (non-breaking change which adds functionality)
- Breaking change (non-backwards-compatible fix or feature)
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Other (please describe)
Explain the steps needed to test the new code to verify that it does indeed address the …
=> github actions merge test

openaerostruct/docs/installation.rst
Doc update to restrict which OM versions are OK.
=> Update OM reqs

README.md, openaerostruct/aerodynamics/geometry.py, openaerostruct/aerodynamics/tests/test_convert_velocity.py, openaerostruct/aerodynamics/tests/test_geometry.py, openaerostruct/aerodynamics/tests/test_lift_drag.py, openaerostruct/aerodynamics/tests/test_mesh_point_forces.py, openaerostruct/aerodynamics/tests/test_pg_transform.py, openaerostruct/aerodynamics/tests/test_rotational_velocity.py, openaerostruct/common/tests/test_reynolds_comp.py, openaerostruct/geometry/tests/test_geometry_mesh_transformations.py, openaerostruct/structures/tests/test_structural_cg.py, openaerostruct/structures/tests/test_weight.py, openaerostruct/structures/wing_weight_loads.py, openaerostruct/transfer/displacement_transfer.py, openaerostruct/transfer/tests/test_compute_transformation_matrix.py, openaerostruct/transfer/tests/test_load_transfer.py, setup.py
Fixed all random seeds so that all tests will be reproducible. Also, replaced `np.random.seed()`with `np.random.default_rng()`, which is a new best practice.
=> Fixed random seeds

setup.py
Motivated by the dependabot security alert, this PR enforces `numpy` version `>=1.14.0` and `scipy>=1.0.0`.
1 day
=> Added lower bounds to numpy and scipy versions

openaerostruct/geometry/ffd_component.py, setup.py
Updated the FFD component because pyGeo recently dropped compatibility with the old function name we use in OAS.
Soon. This PR needs to be merged before #397
=> updated FFD component

README.md
Add paper to cite if using point loads
A day
Documentation update
Previewed the modified .md file.
N/A
=> Add paper to cite if using point loads

README.md
=> Replace GHA builds status badge with Azure

.readthedocs.yaml, CITATION.cff, openaerostruct/docs/index.rst
Added paper links and citation info to the top page of the docs.
#451 should be merged first because that fixes readthedocs config file.
1 day
=> Added citation info to docs

tests/integration_tests/test_scaneagle.py
This PR fixes a total derivative test that was recently broken because OpenMDAO 3.37 changed how the erres are computed in check_totals: https://github.com/OpenMDAO/OpenMDAO/pull/3442
I just tuned FD step size to get a more accurate FD approximation.
1 day
=> Fix a total derivative test

openaerostruct/docs/advanced_features/multi_section_surfaces.rst, openaerostruct/docs/advanced_features/scripts/basic_2_sec_AS.py, openaerostruct/docs/advanced_features/scripts/basic_2_sec_visc.py, openaerostruct/integration/aerostruct_groups.py, openaerostruct/utils/testing.py, tests/integration_tests/test_multi_2_sec_AS.py, tests/integration_tests/test_multi_single_AS.py
Adds support for aerostructural analysis and optimization with multi-section surfaces.
Includes tests. Docs update to come.
1 Day
=> Add aerostructural support for multi-section surfaces

openaerostruct/docs/advanced_features.rst, openaerostruct/docs/advanced_features/stability_derivatives.rst, openaerostruct/examples/stability_derivatives.py
This PR adds a stability derivative example. Closes #431 
No rush.
=> Added a stability derivative example

setup.py, tests/integration_tests/test_multi_single.py
`test_multi_single.py` fails on OpenMDAO 3.40.0 because of a bug in the OM which has been fixed in https://github.com/OpenMDAO/OpenMDAO/pull/3612.
With this PR the test　will be skipped if OM version is 3.40.0.
Also, for now, we upper bound the OM version to 3.39.
Soon
=> Skip a failing test on OM 3.40
